### ISSUE TITLE
Issue with Pkg.add("Mosek") 

### ISSUE THREAD

**Issue by GH310** [JuliaOpt/Mosek.jl#179]
Hello,

I am new to Julia and have just installed JuMP. I am looking to install Mosek.jl as well. I previously had Mosek (complete with license) on my computer. I tried "Pkg.add("Mosek") and got the error " ERROR: LoadError: Failed to get MOSEK download host".

After reading online, I uninstalled MOSEK completely, removed all environment variables manually from my system, deleted the packages in my .julia directory. I then proceeded to do Pkg.add("Mosek") again. And I get exactly the same issue as previously. It seems I have tried everything I can think of and still nothing works.

It would be great to get help on this issue. Please let me know if there is anything I can provide to make things easier. 

Thanks!
Georgina

**Comment by GH310** [comment]
Hello,

I have been interacting with Mosek and it seems that the issue is between a mismatch of versions (the one expected by Mosek.jl is not the one that is delivered by Mosek). See this thread: https://mail.google.com/mail/u/0/#inbox/FMfcgxwChJlBLZgMDlncZJKcnTXVJRhL

They have been unable to resolve this issue. Would it be possible to get some help there? 

Many thanks!
Georgina

**Comment by ulfworsoe** [comment]
Issue resolved here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mosek/gK5dDfiatHg/AUHd-jIuBQAJ

In conclusion: We use `powershell` to download and unpack the distro. It appears that that may be disabled for security reasons causing download and/or unpacking to fail. This is difficult to fix since we need an external program to download+unzip, and powershell is the only reliable option.

A work-around is to download and unpack the relevant distro to the default place ($HOME/mosek) before installing or building `Mosek.jl`.
