### ISSUE TITLE
Update for Julia 0.5

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#95]
Julia 0.5 will be released in the upcoming week or so. The package should be updated to address deprecation warnings.

**Comment by ulfworsoe** [comment]
The head revision should now support 0.5 without warnings (I think). It is probably not compatible with 0.4, mostly due to AbstractString/String.
One problem I have not been able to figure out: Recently I added a test that check the defined values of constants vs. MOSEK's definition (``test/check_consts.jl``). In v0.4 it ran in a few seconds, while in 0.5 it is *extremely* slow. I have disabled it for now.

**Comment by mlubin** [comment]
@ulfworsoe, no idea why it would be slower. If you can pinpoint it to a slowdown in Julia we should report upstream.
